# Generated by Django 6.0 on 2026-02-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_description_payment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('BANK_TRANSFER', 'Bank Transfer'), ('CBE', 'CBE'), ('AWASH_BANK', 'Awash Bank'), ('TELEBIRR', 'TeleBirr'), ('CASH', 'Cash')], max_length=20),
        ),
    ]
