# Generated by Django 6.0 on 2026-02-10 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_menuitem_foodorder_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='calories',
            field=models.CharField(blank=True, help_text='e.g. ~350-370 kcal', max_length=50),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='carbs_pct',
            field=models.CharField(blank=True, help_text='e.g. ~70-75%', max_length=50),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='fat_pct',
            field=models.CharField(blank=True, help_text='e.g. ~1-2%', max_length=50),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='fiber_pct',
            field=models.CharField(blank=True, help_text='e.g. ~3-4%', max_length=50),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='health_benefits',
            field=models.TextField(blank=True, help_text='Benefits of this food item'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='health_considerations',
            field=models.TextField(blank=True, help_text='Considerations (e.g. gluten, sugar)'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='ingredients',
            field=models.TextField(blank=True, help_text='List of ingredients with percentages'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='protein_pct',
            field=models.CharField(blank=True, help_text='e.g. ~12-15%', max_length=50),
        ),
    ]
