# Generated by Django 6.0 on 2026-02-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_roommedia_delete_roomimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='bathroom_type',
            field=models.CharField(blank=True, default='Private', help_text='Bathroom type', max_length=50),
        ),
        migrations.AddField(
            model_name='room',
            name='bed_type',
            field=models.CharField(blank=True, default='Queen Size', help_text='Type of bed', max_length=50),
        ),
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the room'),
        ),
        migrations.AddField(
            model_name='room',
            name='has_air_conditioning',
            field=models.BooleanField(default=True, help_text='Air conditioning'),
        ),
        migrations.AddField(
            model_name='room',
            name='has_balcony',
            field=models.BooleanField(default=False, help_text='Private balcony'),
        ),
        migrations.AddField(
            model_name='room',
            name='has_minibar',
            field=models.BooleanField(default=False, help_text='Minibar available'),
        ),
        migrations.AddField(
            model_name='room',
            name='has_nightwear',
            field=models.BooleanField(default=False, help_text='Nightwear/robes provided'),
        ),
        migrations.AddField(
            model_name='room',
            name='has_safe',
            field=models.BooleanField(default=True, help_text='In-room safe available'),
        ),
        migrations.AddField(
            model_name='room',
            name='has_toiletries',
            field=models.BooleanField(default=True, help_text='Toiletries provided'),
        ),
        migrations.AddField(
            model_name='room',
            name='has_tv',
            field=models.BooleanField(default=True, help_text='Smart TV'),
        ),
        migrations.AddField(
            model_name='room',
            name='has_wifi',
            field=models.BooleanField(default=True, help_text='Free WiFi'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_quality',
            field=models.CharField(choices=[('STANDARD', 'Standard'), ('PREMIUM', 'Premium'), ('LUXURY', 'Luxury'), ('VIP', 'VIP Suite')], default='STANDARD', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='special_features',
            field=models.TextField(blank=True, help_text='Special features of the room'),
        ),
        migrations.AddField(
            model_name='room',
            name='temperature_setting',
            field=models.CharField(blank=True, default='18-24°C', help_text='Room temperature range', max_length=50),
        ),
        migrations.AddField(
            model_name='room',
            name='window_type',
            field=models.CharField(choices=[('OCEAN_VIEW', 'Ocean View'), ('GARDEN_VIEW', 'Garden View'), ('CITY_VIEW', 'City View'), ('POOL_VIEW', 'Pool View'), ('NO_WINDOW', 'No Window')], default='CITY_VIEW', max_length=20),
        ),
    ]
